import {createSlice} from '@reduxjs/toolkit'


const initialState = {
    //empty array that will be used to store the list of programs
    programs : []
}

export const programSlice = createSlice ({
    name : "programs",
    initialState,
    reducers : {
        //setPrograms is an action that updates programs with the data provided in action.payload
        setPrograms: (state, action) => {
            state.programs = action.payload
        }
    }
})

//setPrograms is an action automatically generated by createSlice. It is exported for use in React components
export const {setPrograms} = programSlice.actions
// selectPrograms is a selector that allows access to the state of slice programs in the Redux store
export const selectPrograms = (state) => state.programs
//reducer generated by createSlice is exported by default for use when configuring the Redux store
export default programSlice.reducer
