import {createSlice} from '@reduxjs/toolkit'


const initialState = {
    //empty object that could contain user information
    infos : {},
    //a boolean indicating whether the user is logged in (initially false)
    isLogged : false
}

export const userSlice = createSlice ({
    //Slice name
    name : "user",
    initialState,
    //object containing functions that define how state should be updated in response to specific actions
    reducers: {
        //action that updates info with the data provided in action.payload and sets isLogged to true
        connectUser: (state,action) => {
            state.infos = action.payload
            state.isLogged = true
        },
        //action that resets info to an empty object and sets isLogged to false
        logoutUser: (state) => {
            state.infos = {}
            state.isLogged = false
        }
    }
    
})

//connectUser and logoutUser are actions automatically generated by createSlice. They are exported for use in React components
export const {connectUser, logoutUser} = userSlice.actions
//selector that allows access to the state of the user slice in the Redux store
export const selectUser = (state) => state.user
//reducer generated by createSlice is exported by default for use when configuring the Redux store
export default userSlice.reducer